language: node_js
dist: trusty
node_js:
  - "14"

script:
  - npm test
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: ba912765-df3c-4d60-81ca-773f29f36e2c
  app: agile-project-frontend
  on:
    repo: gherdeguia/agile-project-frontend
