language: node_js
dist: trusty
node_js:
- '14'
script:
- npm install
- npm test
- npm run build
- serve -s build
deploy:
  provider: heroku
  api_key:
    secure: I730mTyWAxhJHKpzqtvOplBohJzmeY679zFo+xgdl+KXGH8uNgNzhVYkxs/fTka+2EpR0XiZ4fgcB3wKwUNTRq9lYAKmPtKwbGWy+jDIKKll5b4MO7Ulyqm4xj9qBvJkr1YLfgR00x7zlQq/imSTNZGbsyZ9WGg3b2MjXWbvsNIB2QQY/dU/TUjg3GfG5bxYZYZClEEeTq94Cqn8xVfCXeGAW2Kww2gS/cqhyTpLqAUCp2IhtTKPVcG5h3fgTxCi8XKyRJ71xViE8cRcf4W4kY1hEq06n7ekfTHdlx0RR3kkHuVWIyW8eaffcF7kQ8fFMUPnOTRNesXAmLSDaDRQXxBqIXjA5NYzPQ+n1SrttZj0/z56BP9WnBwavPWj5WxT/R/2qQQXG/6kjHFmOCVg2xNNAtKjM60gchEksrtBFSJ5udEUFKkFXrJNlE8xfXaCHsCzBirQWSvRwMU4n+cz91EGfZUo0Dp/0nSXf0dGlogMtTm9zYKCW3c+EGW/foJPyaVo5VCUakZ5M/5xL5Z3fmsFNpmDQH7Yczel+leVmjQ+GpKO8AU+Ue/DMxVdr0nPj8zWq2ET/a7bMpYW/ZSjOx3XiQlpl9qWSozhgg8mAqIW/okhA3177Fqey9dLhSIGpyo+mc0yHS/IbCZBdB2j2uA70l0y8WIS0ml7es2Te9g=
  app: cine-q
  on:
    repo: gherdeguia/agile-project-frontend
